version: '3.3'
services:
  db:
    image: mysql:8.0.28
    restart: always
    ports:
      - "3306:3306"
    volumes:
    - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_USER: 'moamoa'
      MYSQL_PASSWORD: 'moamoa'
      MYSQL_DATABASE: 'moamoa'
      TZ: 'Asia/Seoul'
